"""Netscape cookie 文件的读写。

yt-dlp 与 curl 都使用这一格式；它同时是 vidporter 内部的 cookie 交换格式
（扫码登录、浏览器 CDP 导出、yt-dlp 消费，全部经由它）。
"""

from __future__ import annotations

import time
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path


@dataclass
class Cookie:
    name: str
    value: str
    domain: str
    path: str = "/"
    expires: int = 0  # unix 秒；0 表示会话 cookie
    secure: bool = True
    http_only: bool = False


def parse_netscape(text: str) -> list[Cookie]:
    cookies: list[Cookie] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("#HttpOnly_"):
            http_only = True
            line = line[len("#HttpOnly_") :]
        elif line.startswith("#"):
            continue
        else:
            http_only = False
        parts = line.split("\t")
        if len(parts) != 7:
            continue
        domain, _flag, path, secure, expires, name, value = parts
        cookies.append(
            Cookie(
                name=name,
                value=value,
                domain=domain,
                path=path,
                expires=int(expires) if expires.isdigit() else 0,
                secure=secure == "TRUE",
                http_only=http_only,
            )
        )
    return cookies


def write_netscape(path: Path, cookies: Iterable[Cookie]) -> int:
    """写出 Netscape 格式；返回写入条数。"""
    lines = ["# Netscape HTTP Cookie File", "# Generated by vidporter."]
    seen: set[str] = set()
    count = 0
    for c in cookies:
        if c.name in seen:
            continue
        seen.add(c.name)
        prefix = "#HttpOnly_" if c.http_only else ""
        secure = "TRUE" if c.secure else "FALSE"
        expires = c.expires if c.expires > 0 else int(time.time()) + 180 * 86400
        lines.append(
            f"{prefix}{c.domain}\tTRUE\t{c.path or '/'}\t{secure}\t{expires}\t{c.name}\t{c.value}"
        )
        count += 1
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return count


def load_file(path: Path) -> list[Cookie]:
    return parse_netscape(path.read_text(encoding="utf-8", errors="replace"))


def filter_by_domain(cookies: Iterable[Cookie], domain_substring: str) -> list[Cookie]:
    """按域名子串过滤（例如 'bilibili' 匹配 .bilibili.com）。"""
    key = domain_substring.lstrip(".").lower()
    return [c for c in cookies if key in c.domain.lower()]


def from_cdp(cdp_cookies: list[dict]) -> list[Cookie]:
    cookies = []
    for c in cdp_cookies:
        expires = c.get("expires", -1)
        cookies.append(
            Cookie(
                name=c.get("name", ""),
                value=c.get("value", ""),
                domain=c.get("domain", ""),
                path=c.get("path", "/"),
                expires=int(expires) if expires and expires > 0 else 0,
                secure=bool(c.get("secure")),
                http_only=bool(c.get("httpOnly")),
            )
        )
    return cookies


def cookies_for_domain(path: Path, domain: str) -> list[Cookie]:
    """从 cookie 文件里筛出某个域名下可用的 cookie（丢弃已过期项）。"""
    now = int(time.time())
    return [
        c
        for c in filter_by_domain(load_file(path), domain)
        if c.value and (c.expires == 0 or c.expires > now)
    ]


def header_string(cookies: list[Cookie]) -> str:
    """拼成 HTTP ``Cookie`` 头的值。"""
    return "; ".join(f"{c.name}={c.value}" for c in cookies)


def merge(*cookie_lists: list[Cookie], prefer_first: bool = True) -> list[Cookie]:
    """合并多组 cookie，按 name 去重。``prefer_first`` 时先出现的优先。"""
    merged: dict[str, Cookie] = {}
    order = cookie_lists if prefer_first else list(reversed(cookie_lists))
    for cookies in order:
        for c in cookies:
            merged.setdefault(c.name, c)
    return list(merged.values())


def describe(cookies: list[Cookie]) -> str | None:
    """人类可读摘要，用于日志。"""
    if not cookies:
        return None
    names = [c.name for c in cookies]
    if len(names) > 8:
        names = names[:8] + ["..."]
    return f"{len(cookies)} cookies: {', '.join(names)}"
